name: Container Scan with GH packages
on:
  push:
    branches: [ master,docker ]
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: '1.8'  

jobs:
  BUILD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: Build with Maven
      run: mvn package --file pom.xml
    
    - name: Docker Login to GH packages
      run: |
        docker login docker.pkg.github.com -u v-abiss -p ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Tag image
      run: |
        docker build -f ./Dockerfile -t spring-petclinic:${{ github.run_number }} .
        docker tag spring-petclinic:${{ github.run_number }} docker.pkg.github.com/v-abiss/petclinic/petclinic:${{ github.run_number }}
   
    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: docker.pkg.github.com/v-abiss/petclinic/petclinic:${{ github.run_number }}
        
    - name: Push image
      run: |
        docker push docker.pkg.github.com/v-abiss/petclinic/petclinic:${{ github.run_number }}
